### ISSUE TITLE
frontend - possibility to change enrollment status of 'external' player

### ISSUE THREAD

**Issue by michal-marciniec** [michal-marciniec/codeball#91] opened 2016-08-21 14:51 UTC
Users can enroll other players on their behalf, but there should also be possibility to change other player's enrollment status.   

I suggest that admins could change enrollment status of anyone and normal users should be able to change status of players enrolled by them.  

From backend side endpoint /api/{gameId}/enrollment/{userId} may be used.

**Comment by kamilmielnik** [comment] 2016-08-21 16:19
@michal-marciniec 
this is a duplicate of https://github.com/michal-marciniec/codeball/issues/67

**Closed as completed by kamilmielnik** 2016-08-21 16:19 UTC
Labels: frontend
