### ISSUE TITLE
frontend - error box does not scale well

### ISSUE THREAD

**Issue by michal-marciniec** [michal-marciniec/codeball#79] opened 2016-08-12 06:27 UTC
![image](https://cloud.githubusercontent.com/assets/17987592/17614430/97989a86-6066-11e6-8e40-0d28188bce13.png)

**Comment by kamilmielnik** [comment] 2016-08-12 20:31
@michal-marciniec 
I don't understand what the issue is. Do you have a suggestion for improvement?
1. please notice, that you have a long string `org.hibernate.exception.SQLGrammarException` which is placed on a new line instead of breaking it
2. error box on the screenshot is positioned as follows:
   - horizontal margins, 10% of viewport width each
   - top margin, 10% of viewport height
   - fully occupy available width, with a limit of 800 px
3.  user does not manipulate width of the webpage so often (all errors will look the same on the same screen width, ie. device)

**Comment by michal-marciniec** [comment] 2016-08-16 06:12
@kamilmielnik 
You're right, this is more suggestion for improvement more than a bug.
The issue is that when the screen is wide enough the error box avoids to overlap with left-hand menu, but when I narrow the window, instead of the error box becoming higher, it then starts to overlap with the menu.

**Comment by kamilmielnik** [comment] 2016-08-16 17:42
@michal-marciniec 
Would it make more sense to you if the error box was horizontally centered in relation to just the right hand side of the screen (i.e. everything except menu) ?

On mobile devices (e.g. iPhone 5 [320x568]) menu has width of 58px - if we remove that number from error box' width, it leaves really not that much space.

**Comment by kamilmielnik** [comment] 2016-08-16 18:10
This discussion is not pointless since if we ever have another popup, we would position it the same way as errors are positioned.

**Comment by kamilmielnik** [comment] 2016-09-19 18:04
Closing. Can't think of a better way to deal with this.
@michal-marciniec please reopen if you have any suggestions

**Closed as completed by kamilmielnik** 2016-09-19 18:04 UTC
Labels: frontend, improvement
